# scripts/generate_articles.py
import datetime
from pathlib import Path

article_path = Path("articles")

def generate_article():
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d-%H%M")
    file = article_path / f"MooresConstant-{now}.md"
    file.parent.mkdir(parents=True, exist_ok=True)

    content = f"""---
title: Moore's Constant Update - {now}
---

**We are not just made of stardust — we are the Constant. Not the photon.**

> This is an autogenerated summary based on filtered insight, contradiction screening, and Moore's Constant.

Stay curious. This is Yourverse.
"""

    with open(file, "w") as f:
        f.write(content)

if __name__ == "__main__":
    generate_article()
