name: Moore's Constant Content Autopilot

on:
  schedule:
    - cron: '*/15 * * * *'  # Light check every 15 mins
    - cron: '0 0,5,10,15,20 * * *'  # Article generation 5x/day

jobs:
  light_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run light contradiction check
        run: |
          python3 scripts/light_check.py
      - name: Commit log results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add logs/
          git commit -m "Update light check log" || echo "No changes"
          git push

  full_article:
    runs-on: ubuntu-latest
    needs: light_check
    steps:
      - uses: actions/checkout@v3
      - name: Generate Moore's Constant Article
        run: |
          python3 scripts/generate_articles.py
      - name: Commit article
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add articles/
          git commit -m "Publish article" || echo "No changes"
          git push
